export const captureException = (error: Error): void => console.error(error);
